project:
  type: website
  output-dir: docs

website:
  title: "Şeyma's Analytics Lab"
  navbar:
    search: true
    background: primary
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
    tools:
      - icon: github
        href: https://github.com
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://linkedin.com

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      background: light
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd

  page-navigation: true
  back-to-top-navigation: true

  page-footer:
    center: "Şeyma Toksöz · Hacettepe IE · EMU430 · Spring 2026"
    border: true
    background: dark

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
    mainfont: "Nunito"
    monofont: "Fira Code"

editor: visual
